export enum AuthFormState {
  SHOW_LOGIN_FORM = "SHOW_LOGIN_FORM",
  SHOW_SIGNUP_FORM = "SHOW_SIGNUP_FORM",
}

export enum AuthState {
  LOGIN_SUCCESS = "LOGIN_SUCCESS",
  SIGNUP_SUCCESS = "SIGNUP_SUCCESS",
  LOGIN_FAIL = "LOGIN_FAIL",
  SIGNUP_FAIL = "SIGNUP_FAIL",
  LOGOUT = "LOGOUT",
  LOAD_USER = "LOAD_USER",
}
