export enum AuthFormState {
  SHOW_LOGIN_FORM = "SHOW_LOGIN_FORM",
  SHOW_SIGNUP_FORM = "SHOW_SIGNUP_FORM",
}

export enum AuthState {
  LOGIN_SUCCESS = "LOGIN_SUCCESS",
  SIGNUP_SUCCESS = "SIGNUP_SUCCESS",
  LOGIN_FAIL = "LOGIN_FAIL",
  SIGNUP_FAIL = "SIGNUP_FAIL",
  LOGOUT = "LOGOUT",
  LOAD_USER = "LOAD_USER",
}

export enum AddProductState {
  ADD_PRODUCT = "ADD_PRODUCT",
}

export enum NavbarState {
  DESK_TYPE = "DESK_TYPE",
  MOB_TYPE = "MOB_TYPE",
  NAV_TYPE = "NAV_TYPE",
}
